baseURL = 'god464.github.io'
languageCode = 'zh'
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
title = '我的个人博客'
theme="mini"
hasCJKLanguage=true
[taxonomies]
  category='categories'
  tag='tags'
enableGitInfo = true
pygmentsUseClasses=true
pygmentsCodeFences=true
[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = ["asciidoctor-diagram"]
    safeMode = 'unsafe'
    sectionNumbers = true
    [markup.asciidocExt.attributes]
  [markup.highlight]
      anchorLineNos = true
      guessSyntax = true
      linenos = true
      style = 'gruvbox'
[params]
  enableGoogleAnalytics= true
[security]
enableInlineShortcodes = true
